make redis and sentinel a bit more flexible
covermymeds/puppet-redis pull request #15
Opened 2017-05-02 16:33 UTC by dugdigg

These change will help move to the EPEL maintained redis package, and also enable a bit more flexibility for configuring redis and sentinel.

2017-05-02 16:37 UTC, adamcstephens commented on manifests/init.pp
> +  $redis_service      = undef,
These parameter defaults will yield a non-functional module. Any reason not to move the existing strings to the defaults?

2017-05-02 16:37 UTC, adamcstephens commented on manifests/sentinel.pp
> +  $sentinel_service = undef,
Ditto these parameters defaulting to undef will do bad things.

2017-05-02 16:46 UTC, skpy commented on manifests/init.pp
> +# $redis_conf: The configuration file for resis
typo:  `resis`.

2017-05-02 16:46 UTC, skpy commented on manifests/init.pp
> +# $redis_service: The serivce to run for resis
typo: `resis`

2017-05-02 16:58 UTC, adamcstephens commented on manifests/init.pp
> +  $redis_service      = 'redis.service',
I'd recommend setting this to just _redis_ so that its compatible with non-systemd still.

2017-05-02 16:59 UTC, dansajner commented on manifests/init.pp
> +  $redis_conf         = 'redis.conf',
Can you make these variables represent full paths to the config file?  Its odd to make just the filename a param.

2017-05-08 19:59 UTC, pfeff requested changes

2017-05-08 19:59 UTC, pfeff commented on templates/sentinel.conf.erb
> +<% if @confi_32 -%>
Typo: should be config_32

2017-05-08 19:59 UTC, pfeff commented on templates/redis.conf.puppet.erb
> +protected-mode no
Do we need to protect this with an `if @config_32`?

2017-05-09 11:40 UTC, dansajner commented on manifests/init.pp
> +  $redis_conf         = 'redis.conf',
Can you update this to be the full path to match what you did for sentinel?

2017-05-09 11:41 UTC, dansajner commented on manifests/init.pp
> +  $redis_service      = 'redis.service',
Can you update this to just be `redis` to match what you did for sentinel?

2017-05-09 18:59 UTC, dansajner commented on manifests/init.pp
> +  $version            = 'redis-3.0.5-1.el7.cmm.x86_64',
This is not an appropriate default for a public module.  The default should be `installed`.

2017-05-15 19:45 UTC, dansajner commented on manifests/init.pp
> +  if ( $version =~ /^3.2.*/ ) or ( $version == 'installed' ) {
This doesn't scale well as redis version are released.  Can you do `$version >= 3.2`?  Would have to change the variable type to be string or integer.

2017-05-15 21:31 UTC, adamcstephens commented on manifests/init.pp
> +  if ( $version =~ /^3.2.*/ ) or ( $version == 'installed' ) {
There's a dedicated function that's recommended for version comparisons:

https://docs.puppet.com/puppet/4.2/function.html#versioncmp

2017-05-16 13:26 UTC, pfeff approved these changes

2017-05-16 13:35 UTC, dansajner approved these changes
Looks good.  Do you want to add one more commit to bump the version in metadata.json?

2017-05-16 14:21 UTC, adamcstephens approved these changes
Looks good.

I believe this is the first puppet4 only code, so we may want to update the readme.

This seems to include the changes in #14. If so, please close that one.

2017-05-17 12:36 UTC, dansajner commented on manifests/init.pp
> +# $protected - As of version 3.2 you need to set proteced-mode yes or no
This module does not support setting the `bind` configuration item.  I would remove all references to setting the bind IP as an option.

2017-05-17 17:15 UTC, dugdigg commented on manifests/init.pp
> +# $protected - As of version 3.2 you need to set proteced-mode yes or no
😢

2017-05-17 17:15 UTC, dugdigg commented on manifests/init.pp
> +# $protected - As of version 3.2 you need to set proteced-mode yes or no
JK

2017-05-30 17:50 UTC, merged